# ES6为我们提供了优雅的异步控制方法

我们在[ES6概要](https://github.com/zhangwang1990/PracticeModernJavaScript/blob/master/docs/%E7%AC%AC2%E7%AB%A0.%20ES6%20%E6%A6%82%E8%A6%81.md)一章学习了ES6的基本更新，在[Classs,Symbols,Objects拓展 和 Decorators](https://github.com/zhangwang1990/PracticeModernJavaScript/blob/master/docs/%E7%AC%AC3%E7%AB%A0.%20Classes%2CSymbols%2CObjects%20%E5%92%8C%20Decorators.md)一章中学习了符号的使用，我们现在已经具备理解`promises`,`iterator`和`generators`了的基础了。Promises 提供了一种控制异步流的优雅方法，迭代器描述了一个对象将如何被迭代。生成器让异步代码的书写更加优雅，使用生成器写异步代码会让你有写同步代码的感觉。

学习Promise的性价比非常高，绝大多数新的JavaScript/DOM平台的异步API都是基于Promise构建，Promises这个概念其实出现了很久了，社区里很多库很早就对Promise有自己的实现（[`Bluebird`](http://bluebirdjs.com/docs/api/promise.try.html)、[`Q`](https://github.com/kriskowal/q/wiki/API-Reference#promisefcallargs)等），但是直到ES6它才是内置于JS语言。

> 比如node的orm (sequlize)[http://docs.sequelizejs.com/],动态引入组件的`import`语法等等都基于Promise。

## Promises

Promises 可以被看做是一种 “封装和组合未来值的易于复用的机制”，就算我们在Promises链中写的是同步代码，其依旧将异步进行。理解了Promise，复杂的异步流也会变得容易理解，我们再也不用经历回调地狱的噩梦了。

### Promises 启式--基本用法

我们以浏览器的新API--`fetch`为例来说明Promise该如何使用，这个API提供了一个获取资源的接口，其提供了强大而灵活的功能集。下面是`fetch`的一个简单使用示例，用一行代码添加了一个HTTP `GET/items`请求：

```js
fetch('/items')
```

光`fetch('/items)`这条语句其实并没啥好说的，它向`/itmes`发送了一个`GET`请求，只用这条语句不能获取其返回值也不能判断请求是否成功了。`fetch`方法的返回值实际上就是一个`Promise`，它允许我们在之后链式调用`.then`方法，紧接着的`.then`中的回调函数将会在`/items`资源加载结束之后被立即调用，并且会以请求结果为其参数（这里我们命名为`response`）。

```js
fetch('/items').then(response => {
  // do something
})
```

一般我们会按照下面这样使用`fetch`。`fetch`执行后会返回一个`Promise`对象，之后你可以使用`.then`,`.catch`给返回结果添加处理函数：

```js
const p = fetch('/items')
p.then(res => {
  // handle response
})
p.catch(err => {
  // handle error
})
```

如果`fetch('/items')`执行成功，将会触发`p.then(..)`中的处理函数，同时会以返回值作为这个函数的参数。如果`fetch('item')`执行失败，则将触发`p.catch()`中的处理函数，我们还可以把拒绝处理函数当做`.then`的第二个参数，如下所示，这两种写法是等价的：

```js
const p = fetch('/items')
p.then(
  res => {
    // handle response
  },
  err => {
    // handle error
  }
)
```

另外我们其实也可以省略`fulfilled`时的处理函数，下述代码中`.then(null,rejection)`和`.catch(rejection)`具有相同的功能。

```js
const p = fetch('/items')
p.then(res => {
  // handle response
})
p.then(null, err => {
  // handle error
})
```

> #### Promise 是一种可替代回调函数和事件进行异步操作的方案
> 传统的JavaScript依赖于回调而非链式的Promise。如果`fetch`也需要回调函数，我们则需要添加一个回调函数供`fetch`操作结束时调用。Node.js的典型异步代码为我们展现了一种好的实践模式，即保证回调函数中的第一个参数为`error`,虽然错误只是可能发生的。参数的剩余部分则被用做读取异步操作的结果。如果`fetch`使用回调处理结果，将会长下面这样：
> 
> ```js
> fetch('/items', (err, res) => {
  if (err) {
    // handle error
  } else {
    // handle response
  }
})
> ```
> 
> 在`/items`资源被找到之前回调函数不会被触发。这样的执行也是异步的非阻塞的。不过使用回调你只能声明一个函数，使用者需要在这一个回调函数中对返回值进行所有的处理。
> 
> 除了传统的回调函数，另一种异步API设计会使用事件驱动模型。如果`fetch`采用事件驱动，则需要绑定所有需要的事件处理函数，就类似我们给DOM绑定事件监听器一样。一般说来会存在一个`error`事件用以应对错误，其它的一些事件监听器用以响应相应的事件，此时的`fetch`会是下面这样：
> 
> ```js
> fetch('/items')
  .on('error', err => {
    // handle error
  })
  .on('data', res => {
    // handle response
  })
> ```
> 
> 为不同的事件绑定多个监听器可以消除前面回调函数中需要集中在一个函数对返回值进行所有的处理的担忧。不过事件存在另外一个问题，它使得链式调用难易维护，我们很难控制事件的发生顺序，而promise机制正好可以同时应对这两个难点。值得说明的是事件驱动机制更适用于处理流值，而Promise在这种情况下其实不是那么合适，我们将在[Asynchronous Code Flows ]()一节更细致的讨论不同情况的合适的异步控制机制。
> 

当讨论到`promises`时，链式调用可能是最让人疑惑的一点，在基于事件的API中，我们可以通过`.on`方法绑定事件监听器进行处理。Promise则有所不同每个`.then`和`.catch`方法都会返回一个新的`promise`，记住这一点非常重要，通过多层的`.then`和`.catch`我们可以应对多种不同的情况。


> #### 可视化的链式Promises：迷惑的主源
> `.then`和`.catch`方法每次都会返回一个新的`Promise`，这创造了 一个树形结构，假如说现在有一个`p1`promise和由`p1.then`返回的`p2`promise，`p1`和`p2`将由`p1.then`相连。`p1.then()`创造了新的promise`p2`，依附在树上，作为promise `p1`的子枝。
> 
> 当我们链式使用Promise时，我们需要理解 `p1.then(r1).then(r2)` 实际上创建了两个新的promise `p1` 和 `p2`。如果`p2`的决议为完成，处理函数`r2`会被触发，同样`r1`会在`p1`的决议为完成时（fulfill）被触发。当我们有类似`p1.then(r1);p1.then(r2)`这样的声明时，`r1`和`r2`在`p1`的决议为完成（fulfill）时都会被触发，这和前面的`p1.then(r1).then(r2)`有所不同，这句代码中`r2`需要在`p2`的决议也为`fulfull`时才会被触发。
> 
> 弄清楚promise的树形本质是深入理解promise行为的关键。基于此，我创建了一个名为[`Promisees`](https://bevacqua.github.io/promisees/)的在线工具，它让我们可以可视化的观察Promise的链式树形结构，如图4-1所示。
> ![Figure 4-1. Promisees lets you write a piece of code and visualize how the underlying graph evolves as promises are settled in fulfillment or rejection](https://ponyfoo.com/books/practical-modern-javascript/img/pmjs_0401.png)
> 

创建新的Promise有多种方法，通过传递一个 resolver 函数给`Promise`构造函数时，一个promise就把创建了，`resolver`函数接收`resolve`和`reject`两个方法作为参数，如果`resolve`方法执行，则返回的Promise的决议为`fulfill`,如果`reject`方法被执行则返回的`Promise`的决议为`reject`。在Promise构造函数中上述两个方法处理之前，程序将处于`pending`状态，之后所有的附加函数都不会被执行。下述代码中我们使用Promise构造函数生成了一个Promise，并在1s后使用随机函数来决定程序是调用`resolve`还是`reject`。

> 值得注意的是Promise构造函数是被同步执行的。

```js
new Promise(function (resolve, reject) {
  setTimeout(function () {
    if (Math.random() > 0.5) {
      resolve('random success')
    } else {
      reject(new Error('random failure'))
    }
  }, 1000)
})
```

直接调用`Promise.resolve` 或 `Promise.reject`也能创建Promise，其区别在于`Promise.reject`会立即创建一个决议为`reject`的Promise，而`Promise.resolve`创建的Promise的决议可能是`fulfill`也可能是`reject`.

```js
Promise
  .resolve({ result: 123 })
  .then(data => console.log(data.result))
// <- 123
```

当promise `p` 的决议为`fulfill`时，`p.then` 中的回调函数将被执行，当`p`被的决议值为`reject`时，`p.catch`中的回调函数将被执行。这两种情况可能产生三种不同的返回值，固定值，`Promise`/`thenable`对象 或者`throw`一个错误。`thenables`可以被看做类promise的对象，使用`Promise.resolve()`就将其转换为真实的Promise对象，在[Creating a Promise from Scratch.]()一节中我们可以看得更清楚这个过程。

1. 如果处理函数返回的结果是一个确定值，`.then`返回的promise的决议将会是`fulfill`，会继续调用之后的`.then`，如下代码说明了这个过程：

```js
Promise
  .resolve(2)
  .then(x => x * 7)
  .then(x => x - 3)
  .then(x => console.log(x))
// <- 11
```

2. 如果处理函数的返回值是一个Promise，在返回的promise获得决议值之前，`.then()`中的处理函数会一直处于阻塞状态，下面代码中，我们使用`setTimeout`构建了一个异步函数来说明这个道理：

```js
Promise
  .resolve(2)
  .then(x => new Promise(function (resolve) {
    setTimeout(() => resolve(x * 1000), x * 1000)
  }))
  .then(x => console.log(x))
// <- 2000
```

3. 如果处理函数抛出错误，这会使得`.then`返回的Promise的决议值将会是`reject`，这会导致之后的`.catch`中的处理函数被执行，并已抛出的错误作为这个函数的参数。下面的代码展示了这个过程，当`fetch`执行时，触发的处理函数会抛出错误，导致当前`.then`返回的Promise的决议值为`reject`,使得之后的`.catch`中的拒绝处理函数被触发。

```js
const p = fetch('/items')
  .then(res => { throw new Error('unexpectedly') })
  .catch(err => console.error(err))
```


### Promise 进阶 -- 连续的链式调用

通过前一节的学习，我们知道我们可以链式的调用无限的`.then`,每个`.then`都会返回一个新的`promise`。你肯定会好奇Promise为什么会有这样的特性呢？Promise又将如何处理错误。

当我们适用`Promise`构造函数构建新的Promise对象时，如果resolver(决议器)中发生错误，我们可以使用`p.catch`捕捉错误，如下所示：

```js
new Promise((resolve, reject) => reject(new Error('oops')))
  .catch(err => console.error(err))
```

如果resolver调用了`reject`,生成的Promise的决议将会为`reject`，也会触发之后`.catch()`的执行，如下所示：

```js
new Promise((resolve, reject) => { throw new Error('oops') })
  .catch(err => console.error(err))
```

如果`.then()`中的fulfill处理函数报错，也会触发后续的`.catch`函数，下述代码可以说明这个问题：

```js
Promise
  .resolve(2)
  .then(x => { throw new Error('failed') })
  .catch(err => console.error(err))
```

我们把每次链式的结果存储在变量中来更好的说明这个过程。如果你把`.catch`添加到了`p1`后，你将不能捕获到由`p1.then`导致的错误。这是因为当`p1`决议后生产的`p2`是一个全新的primise，它是`p1.then`的被`reject`后的结果。如果我们想要捕获它产生的错误，则需要在`p2`后面添加了`.catch`：

```js
const p1 = Promise.resolve(2)
const p2 = p1.then(x => { throw new Error('failed') })
const p3 = p2.catch(err => console.error(err))
```

下面是另外一种方案，它可以帮助你把`promise`视为树形结构，观察图4-2，我们可以清楚的发现由于错误发生在`p2`节点，我们不能把它交给`p1`的错误处理程序。

![Figure 4-2. Understanding the tree structure of promises reveals that rejection reactions can only catch errors that arise in a given branch of promise-based code.](https://ponyfoo.com/books/practical-modern-javascript/img/pmjs_0402.png)

为了处理`p2`中的错误，我们需要给`p2`添加异常处理函数，如图4-3 所示

![Figure 4-3. By attaching a rejection handler on the branch where an error is produced, we’re able to handle the rejection.](https://ponyfoo.com/books/practical-modern-javascript/img/pmjs_0403.png)

现在我们知道了，处理函数连接在那个Promise后是非常重要的，它决定了它能接受那些错误，不能接收那些错误。值得注意的是如果promise链中未设置错误处理函数，其将被默认设置为`.catch(e=>e)`,会直接传递前面产生的错误，这导致如果当Promise链中有未捕获的错误时，其之后的错误处理函数都可能捕获它。下例中，我们在`p1`和`p2`之间引入了一个中间的`then`，错误在此发生，我们在`p4`后添加了`reject`处理函数，由于`p2`的决议值为`reject`，将导致`p3`的默认错误处理函数被触发，其决议也将是`reject`，这将导致`p4`后的拒接处理函数被触发了。

```js
const p1 = Promise.resolve(2)
const p2 = p1.then(x => { throw new Error('failed') })
const p3 = p2.then(x => x * 2)
const p4 = p3.catch(err => console.error(err))
```

由于p4的拒绝处理器`.catch`并未导致任何错误，所以p4的决议值其实是`fullfill`，这意味着如果p4后面还有`.then`，其将被继续被执行。下面的例子将说明这个问题，`p3`的决议值为`reject`导致`p4`的`.catch`函数被触发，但是p4的`.catch`被为报错，导致`p4`的决议值其实是`fulfill`,使得之后的将指向`fulfill`函数。

```js
const p1 = Promise.resolve(2)
const p2 = p1.then(x => { throw new Error('failed') })
const p3 = p2.catch(err => console.error(err))
const p4 = p3.then(() => console.log('crisis averted'))

/*
Error: failed
    at p1.then.x (<anonymous>:2:33)
    at <anonymous>
crisis averted
*/
```


类似的，如果`p3`的的决议值为`reject`，我们可以使用之后的`.catch`继续捕获它。下面的代码表明`p2.catch`中抛出的错误是可以被`p3.catch`捕获的:

```js
const p1 = Promise.resolve(2)
const p2 = p1.then(x => { throw new Error('failed') })
const p3 = p2.catch(err => { throw new Error('oops') })
const p4 = p3.catch(err => console.error(err))
```

下面的代码则只好打印一次`err.message`.只是因为第一次`.catch`是正常执行的，并未报错,导致其所返回的`promise`的决议其实是`fulfill`,所以紧接其后的`.catch`不会被触发：

```js
fetch('/items')
  .then(res => res.a.prop.that.does.not.exist)
  .catch(err => console.error(err.message))
  .catch(err => console.error(err.message))
// <- 'Cannot read property "prop" of undefined'
```

下面的的代码则会打印两次`err.message`,`p`中的代码由于引用了未定义的变量导致系统报错，之后的两个`.catch`都是直接连接在`p`上的。两个`.catch`处理的都是同一个错误,因此都会被执行：

```js
const p = fetch('/items').then(res =>
  res.a.prop.that.does.not.exist
)
p.catch(err => console.error(err.message))
p.catch(err => console.error(err.message))
// <- 'Cannot read property "prop" of undefined'
// <- 'Cannot read property "prop" of undefined'
```

我们已经知道，通过`then`,一个promise可以被任意链式延伸，如上面代码所示那样，你可以保存promise链中的任意一点的引用，然后基于它生成更多的promise，这也是理解promise的关键点之一：

我们以下述代码为例来说明promise链式调用中发生的所有事件及这些事件是如何被处理的。

```js
const p1 = fetch('/items')
const p2 = p1.then(res => res.a.prop.that.does.not.exist)
const p3 = p2.catch(err => {})
const p4 = p3.catch(err => console.error(err.message))
```

下面我们一步步来讲，上述代码执行过程中究竟发生了什么：

1. `fetch`返回了一个全新的`p1`promise；
2. 如果`p1`执行成功，`p1.then`将返回一个全新的p2 promise；
3. 如果`p2`被拒绝，`p2.catch`将返回一个全新的promise p3;
4. 如果`p3`被拒绝，`p3.catch`将返回一个全新的promise p4;
5. 当`p1`顺利执行，`p1.then`中的处理函数将被执行；
6. 随后由于`p1.then`中发生了错误，`p2`被拒绝了；
7. 由于`p2`被拒绝，`p2.catch`被执行，`p2.then`也随之被忽略；
8. 由于`p2.catch`是正常执行的，所以p3是fulfilled的；
9. 由于p3是顺利执行的，`p3.catch`将永远不会被执行，如果存在`p3.then`，其将被执行

promise是树形结构。
重要的事情说三遍，
promise是树形结构
promise是树形结构
promise是树形结构

我们用图4-4来强化这一概念：

![Figure 4-4. Given the tree structure, we realize that p3 is fulfilled, as it doesn’t produce an exception nor is it rejected. For that reason, p4 can never follow the rejection branch, given its parent was fulfilled.](https://ponyfoo.com/books/practical-modern-javascript/img/pmjs_0404.png)

所有这一切都从单个`promise`开始，然后随着你不断的添加`.then`,`.catch`。promise树就变得枝繁叶茂了。

### 从头构建一个Promise

我们知道。通过`fetch`,`Promise.resolve`,`Promise.reject`或者`Promise`构造函数都可以用来生成Promise。我们已在上文的众多例子中大量使用`fetch`来构建`promise`。我们来看看另外几种创建promise的方法具有哪些差别。

Promise可以通过`new Promise(resolver)`从头构建，`resolver`参数是一个可以用以决议promise的函数，`resolver`参数接收两个函数做为参数，`resolve`函数和`reject`函数。

下面的两个promise的决议值分别被设置为了`fulfill`和`reject`，这里我们设置决议值为`fulfill`的Promise返回值为`result`,而第二个Promise则通过一个`Error`对象设置其决议值为`reject`，并传递`reason`为其信息。

```js
new Promise(resolve => resolve('result'))
new Promise((resolve, reject) => reject(new Error('reason')))
```

> 需要注意的是`resolve`和`reject`是两个内置函数

不给`resolve`函数或`reject`函数传值也是可以的，但是这种情况的用途不多。我们通常会希望决议值为`fulfill`时会返回一个值，也肯定会希望决议为`reject`时能明确的知道其被拒绝的理由，把原因包裹在`Error`对象中可以帮助我们跟踪错误。

promise解析器天生就不是同步进行的。`fulfill` 和 `reject` 的语句都是完全异步执行的。即使解析器是立即调用`resolve`的，直到下一次事件循环，结果才会被返回，这是`promises`的核心要点，保证了所有的结果都在未来发生，下面的例子创建了一个在2s后执行的`promises`.

```js
new Promise(resolve => setTimeout(resolve, 2000))
```

值得注意的是或成功或拒绝，决议只会发生一次，一个promise一旦被决议，它的值就不会再改变。下述代码中，我们创建了一个promise，它的`resolve`在一定的`delay`后执行，而`reject`会在3s后执行。通过传入不同的delay，我们可以观察到`promise`会返回了不同的值，这个值是`resolve`或`reject`中的一个。

```js
function resolveUnderThreeSeconds(delay) {
  return new Promise(function (resolve, reject) {
    setTimeout(resolve, delay)
    setTimeout(reject, 3000)
  })
}
resolveUnderThreeSeconds(2000) // becomes fulfilled after 2s
resolveUnderThreeSeconds(7000) // becomes rejected after 3s
```

当创建一个新的 promise `p1`时，其值可以是你通过另外一个 promise `p2`调用`resolve`获得的,在`p2`获取到结果之前，`p1`将被阻塞。一旦`p2`完成，`p1`将获得其值作为结果。下述代码在效果上和`fetch('/items')`一致。

```js
new Promise(resolve => resolve(fetch('/items')))
```

需要注意的是这种行为只对使用决议器中的`resolve()`有效的。如果你使用`reject()`来执行上述代码，你会发现`p1`promise将会以`p2` promise 整体做为理由被拒绝。`resolve`的决议值可以是`fulfill`或者`reject`。`reject`则永远只会返回决议值为 `reject` 的promise。如果你的`resolve`中是一个被拒绝的promise或者最终被拒绝，你的resolve返回的prmise也会是被拒绝的。而如果你使用`reject`当做决议器`resolver`，无论什么值被传递给`reject`函数结果都会是reject。

在一些情况下，你会预先知道你想设置的promise的值。在这些情况下，你可以从头创建一个promise，如下所示，这在你想利用Promise的链式调用但是又没有一个明显的类似`fetch`这样的创始器时非常方便。

```js
new Promise(resolve => resolve(12))
```

不过如果你仅仅想要的是一个带有预设值的promise，上述代码依然有些冗长，使用`Promise.resolve`会更简洁。下述代码和上述代码的功能一致。二者仅仅在语义上有所区别，下面的这种写法让你避免了写`resolve`函数，可读性也更好。

```js
Promise.resolve(12)
```

像前面我们看到的`resolve(fetch)`那个例子一样，我们可以在`Promise.resolve()`中传入另外一个`promise`或者`thenable`对象，来生成promise。下述代码展现了如何使用`Promise.resolve`转换`thenable`对象为一个合适的promise，之后我们可以像对待正常的promise一样使用它。

```js
Promise
  .resolve({ then: resolve => resolve(12) })
  .then(x => console.log(x))
// <- 12
```

当你知道`promise`的拒绝理由时，你也可以使用`Promise.reject`。下述代码依据一个特定的理由创建了一个被拒绝的`promise`。你可以使用`Promise.reject`中的处理函数动态的替换`throw`语句。`Promise.reject`还可以作为箭头函数的返回值:

```js
Promise.reject(reason)
fetch('/items').then(() =>
  Promise.reject(new Error('arbitrarily'))
)
fetch('/items').then(() => { throw new Error('arbitrarily')})
```

在实际开发者，我们使用`new Promise`构建新Promise的的机会也许并不多，promise构造函数一般被支持promise的库或者类似`fetch`这样的内置函数直接调用，考虑对`.then`和`.catch`提供了树状的promise，一次调用`new Promise`是足够的，不管如何，理解promise是如何创建的对理解基于promise的异步流控制是非常必要的。

### promise的状态和命运

Promise可以处于三种不同的状态，处理中(pending),完成(fulfilled)和被拒绝(rejected)。处理中是其默认状态，之后一个Promise可以转变为完成态或拒绝态。

一个Promise只能被决议一次(`fulfill`或`reject`),当一个Promise被决议后返回了一个非promise或非`then`形态的值时，我们认为其决议值为`fulfill`，当一个promise被拒绝时，其决议值为`reject`。

如果 promise `p1` 决议并返回另外一个 promise 或`then`形态的 `p2` 时，它将依旧处于pending态，但是`p1`依旧是被决议了的，它不能被完成或被拒绝第二次。当`p2`决议时，返回的值将被传递给`p1`。

一旦一个promise的决议值为`fulfill`，`p.then`中的处理函数将立即被执行。如果决议值为`reject`,`p.catch`中的处理函数将立即被执行。

下面这个典型的例子展示了你可以怎么样构建一个`fetch`请求，并在`.then`的处理函数中创建第二个`fetch`promise。第二个`fetch`只有在第一个`fetch`顺利进行时才会被执行。之后的`console.log`语句也只有在第二个promise顺利进行后才会执行，打印出`done`.

```js
fetch('/items')
  .then(() => fetch('/item/first'))
  .then(() => console.log('done'))
```

更加典型的例子常常包含其它的步骤。下面的代码中，我们基于第一个`fetch`返回的结果构建第二个请求。为了达到这个效果，我们使用`res.json`方法，这个方法将解析返回的JSON为对象，之后返回一个新的promise。随后我们基于这个解析值来发起第二个`fetch`请求，最后我们打印出第二个`fetch`请求获得的`item`值。

```js
fetch('/items')
  .then(res => res.json())
  .then(items => fetch(`/item/${ items[0].slug }`))
  .then(res => res.json())
  .then(item => console.log(item))
```

我们并不需要返回`promise`或`thenable`对象，`.then`和`.catch`可以返回值。这些值将被链条中的下一个处理函数接收。从这个角度看来，处理函数以上一个处理函数的结果作为下一个处理函数的输入参数。下面的例子中，我们首先成功处理`[1,2,3]`并返回一个promise，接着在`.then`中遍历这些返回值得到`[2,4,6]`。在随后的链式调用中，我们打印出这些值。

```js
Promise
  .resolve([1, 2, 3])
  .then(values => values.map(value => value * 2))
  .then(values => console.log(values))
  // <- [2, 4, 6]
```

值得注意的是，通过拒绝链，你也可以可以转换数据的，就像我们在[从头构建primise]()一节中看到的一样，`.catch`如果执行无误，并且不返回一个拒绝promise，它将调用之后的链式调用中的`.then`对应的处理函数。


### Promise#finally 提案

TC39有一个提案涉及到`Promise#finally`方法，这个`finally`方法在Promise的决议无论为`fulfill`还是`reject`时都会被触发。

我们可以用下述代码模拟`Promise#finally`。下述代码中，我们让 `fn`在`promise`的决议值为`fulfill`和`reject`时都执行。

```js
function finally(p, fn) {
  return p.then(
    fn,
    fn
  )
}
```

这里有些许的语法不同，首先，传递给 `Promise#finally` 的处理函数不接受任何参数，这是因为这个 promise 即可能是顺利进行的返回值，也可能是拒绝的理由。开发者可以用 `Promise#finally` 的一个变体来隐藏在获取请求和请求结束时需要显示的加载器，这时候我们不需要获得`promise`的决议值究竟是什么就能正确的达到效果。下述代码是一个高级版的ponyfill，它未传递任何参数个任何处理函数。

```js
function finally(p, fn) {
  return p.then(
    () => fn(),
    () => fn()
  )
}
```

传递给`Promise#finally`的处理函数将会处理父promise的结果

```js
const p1 = Promise.resolve('value')
const p2 = p1.finally(() => {})
const p3 = p2.then(data => console.log(data))
// <- 'value'
```

这和`p.then(fn,fn)`有所不同，`p.then(fn,fn)`将产生一个新的promise，如下所示：

```js
const p1 = Promise.resolve('value')
const p2 = p1.then(() => {}, () => {})
const p3 = p2.then(data => console.log(data))
// <- undefined
```

下述代码是`Promise#finally`的一种完整的ponyfill：

```js
function finally(p, fn) {
  return p.then(
    result => resolve(fn()).then(() => result),
    err => resolve(fn()).then(() => Promise.reject(err))
  )
}
```

注意，如果传递给`Promise#finally`的处理函数被拒绝了或者报错了，那么这个由`Promise#finally`返回的promise，将以这个拒绝理由被返回，如下所示：

```js
const p1 = Promise.resolve('value')
const p2 = p1.finally(() => Promise.reject('oops'))
const p3 = p2.catch(err => console.log(err))
// <- 'oops'
```

在仔细阅读上述ponyfill之后，我们可以观察出，如果任何一个表达式中的处理函数出错，这个promise的决议值都会是`reject`。

### 使用`Promise.all`和`Promise.race`

当写异步代码时，有些异步任务会依赖其它异步任务，所以它们必须按照一定顺序执行。同样也存在一些不需要依赖其它异步代码结果的任务，它们其实是可以一起执行的。我们已经知道Promises对异步顺序代码流的控制是非常优秀的，（基于单个的promise可以触发一条事件链），Promises为同时执行的异步代码提供了两个方法，`Promise.all`和`Promise.race`.

在大多数情况下，你会希望代码得以同步进行，这样的代码可以运行得更快，假设你想把两个产品的描述添加到你的目录中。像下面这样，使用两次调用，然后分别使用`console`打印它们是一种方法。虽然最终结果类似，但是我们却需要分开使用两次`fetch`:

```js
fetch('/products/chair')
  .then(r => r.json())
  .then(p => console.log(p))
fetch('/products/table')
  .then(r => r.json())
  .then(p => console.log(p))
```

`Promise.all`方法接收一组promise，并返回一个promise。当所有传入`Promise.all`的primise完成时，`p`的决议值就是`fulfill`并接收一个数组作为之后的函数的参数，该数组里面元素的顺序为之前的promise的调用顺序，如果之前的promise中有一个被拒绝了，`p`就被立即处理为拒绝。下面的例子中就使用了`Promise.all`来接收两个产品并使用一个`console`打印出两个结果。

```js
Promise
  .all([
    fetch('/products/chair'),
    fetch('/products/table')
  ])
  .then(products => console.log(products[0], products[1]))
```

考虑到结果以数组的形式呈现，复数形式的数组语义化并不好。采用参数解构来展示每一种商品的名称能让我们的代码的可读性更好。下述代码就使用了解构。值得注意的是，尽管只有一个参数，在箭头函数中使用解构，单个参数也需要包含在一个圆括号中。

```js
Promise
  .all([
    fetch('/products/chair'),
    fetch('/products/table')
  ])
  .then(([chair, table]) => console.log(chair, table))
```

如果一个promise被拒绝了，`p`会立即被拒绝。立即这一点很重要，因为一个拒绝Promise，可以防止一系列成功执行的promise失效。下述代码中，在`p2`和`p3`执行之前，`p`就立即被拒绝了：

```js
const p1 = Promise.reject('failed')
const p2 = fetch('/products/chair')
const p3 = fetch('/products/table')
const p = Promise
  .all([p1, p2, p3])
  .catch(err => console.log(err))
  // <- 'failed'
```

总的来说，`Promise.all`有三种可能的结果：

- 所有的Promise的决议为`fulfill`，返回的Promise的决议值就是`promise`；
- 只要一个依赖的Promise被拒绝，其结果就立即被拒绝；
- 只要有一个依赖项还出来进行中状态并且没有依赖项被拒绝，就依旧处于进行中状态；

`Promise.race`和`Promise.all`在很多方面类似，不同之处在于第一个fulfill的依赖项被设置为胜利，其结果也将被传递给之后的函数。

```js
Promise
  .race([
    new Promise(resolve => setTimeout(() => resolve(1), 1000)),
    new Promise(resolve => setTimeout(() => resolve(2), 2000))
  ])
  .then(result => console.log(result))
  // <- 1
```

一个Promise为`reject`也将结束竞争，使用`Promise.race`在我们想控制某个请求的时间这种场景下非常有用。比如说，下述代码中，存在一个`fetch`和一个5s内拒绝的promise的竞争，如果请求时间超过5秒，竞争的返回的promise的决议值将会是`reject`。

```js
function timeout(delay) {
  return new Promise(function (resolve, reject) {
    setTimeout(() => reject('timeout'), delay)
  })
}
Promise
  .race([
    fetch('/large-resource-download'),
    timeout(5000)
  ])
  .then(res => console.log(res))
  .catch(err => console.log(err))
```

> 此外，值得注意的是，`Promise.all([])`将被立即执行，而`Promise.race([])`则永远处于`pending`状态.`.then`中如果是异步代码将在下次循环中执行，如果是同步代码则在本次循环的最后被执行。

## 迭代器协议和迭代协议

ES6为JavaScript提供了两种新的协议，迭代器和可迭代对象。这两者新协议被用以定义任何可迭代对象的迭代行为，本节中我们将以学习如何转换一个对象为可迭代序列开始，随后，我们将看看迭代器可以如何定义无线序列，最后，我们将复习实际定义迭代对象时需要有哪些考虑。

### 理解迭代原则

通过给任何一个对象的`Symbol,iterator`分配方法，该对象都可以被迭代。任何时候一个对象被迭代时，该对象的`Symbol.iterator`对应的方法就会被调用。

在[ES6 Essentials]()一节中，我们已经介绍过拓展运算符了，它是ES6中少数的几种利用迭代协议的特性。如下代码所示，当对一个假设的迭代对象使用拓展运算符时，一个对象需要调用`symbol.iterator`所对应的方法,返回的迭代器将被用做获取对象的值。

```js
const sequence = [...iterable]
```

你可能还记得，符号属性不能直接用做对象字面属性，下述代码表明了使用ES6之前的语法如何添加符号属性

```js
const example = {}
example[Symbol.iterator] = fn
```

在这里，我们将使用计算属性名来书写字面量模式的对象符号属性，这种写法比前面的更加简洁，如下所示：

```js
const example = {
  [Symbol.iterator]: fn
}
```

分配给`Symbol.iterator`的方法必须返回一个准守迭代器协议的对象。这个协议定义了如何从一个迭代序列中获取值。协议规定迭代器必须是一个包含`next`方法的对象，`next`方法不接收参数并且应该返回以下两种属性的对象：

- `value` 属性：序列中的当前项；
- `done` 属性：一个判别当前序列是否结束的布尔值；

我们使用下述代码来帮助我们理解迭代协议。通过添加`Symbol.iterator`属性，我们转换一个序列对象为一个迭代器。迭代器将返回一个可迭代对象，每次调用`next`，`items`数组中的下一项将被提供，当`i`为最后的`items`数组最后的索引值时，我们将获得`donw:true`,这意味着迭代结束了。

```js
const items = ['i', 't', 'e', 'r', 'a', 'b', 'l', 'e']
const sequence = {
  [Symbol.iterator]() {
    let i = 0
    return {
      next() {
        const value = items[i]
        i++
        const done = i > items.length
        return { value, done }
      }
    }
  }
}
```

JavaScript是一门渐进式的语言，新特性在以不破坏就特性的基础上被添加。也由于这个原因，迭代器不能利用已有的遍历语法,如`forEach`,`for..in`等等。ES6为我们提供了一些专用的遍历迭代器的语法:`for..of`,`...`拓展运算符以及`Array.from`。

`for...of`方法可以被用做遍历迭代器，下述代码展示了我们如何使用`for...of`来迭代前面我们创建的`sequence`对象：

```js
for (const item of sequence) {
  console.log(item)
  // <- 'i'
  // <- 't'
  // <- 'e'
  // <- 'r'
  // <- 'a'
  // <- 'b'
  // <- 'l'
  // <- 'e'
}
```

我们已经知道给普通的对象添加`Symbol.iterator`可将其转换为可迭代对象。不过ES6也为我们提供了一些原生的可迭代对象，`Array`,`String`,`NodeList`，以及函数的`arguments`对象都是，对它们都可以直接使用`for...in`。使用`...`拓展运算符和`Array.form`则可以获取由可迭代对象的各个值组成的数组，`Array.from`还可以转换类数组对象（具有`length`属性，属性名为0，1，2...的对象）为真数组：

```js
console.log([...sequence])
// <- ['i', 't', 'e', 'r', 'a', 'b', 'l', 'e']
console.log(Array.from(sequence))
// <- ['i', 't', 'e', 'r', 'a', 'b', 'l', 'e']
console.log(Array.from({ 0: 'a', 1: 'b', 2: 'c', length: 3 }))
// <- ['a', 'b', 'c']
```

总的来说，具有`[Symbol.iterator]`方法的对象将遵循迭代协议，这意味着这种对象是可迭代的，迭代方法只需要执行一次就可以迭代完整个对象，并返回一个代表该对象的迭代对象。为了实现迭代，我们可以使用`for..of`,`...`拓展运算符或`Array.from`。

本质上，迭代协议的亮点在于为集合和类数组对象提供了一种高效的迭代方法。有能力定义任何对象如何被迭代是一件非常有意义的事情，因为它将使得各种库以ES原生的方法来实现迭代，实现迭代的方法不复杂，而且还不会破坏现有的代码。

```js
for (const element of $('li')) {
  console.log(element)
  // <- a <li> in the jQuery collection
}
```

可迭代的序列并不要求是有限的，它也可以拥有无限的元素，下面我们深入探讨这个话题及其应用。


### 无限序列

迭代器天生是懒惰的。迭代序列中的元素即使是有限的，一次只会生成一个。注意，无限序列不能没有惰性属性来表达。一个无限序列不能被表现为一个数组。这意味着如果使用拓展运算符或者`Array.from`转换一个无限队列为数组将导致JS报错，因为这将导致我们进入一个无限循环。

下面代码表现出了一个由0到1之间的浮点数组成的无限序列迭代器，观看代码我们可以发现，由`next`返回的项目甚至没有一个值为`true`的`done`属性（表征序列结束）。它使用两个箭头函数隐式返回对象。第一个箭头函数用以返回用于迭代无限数字序列的迭代器对象。第二个箭头函数获取迭代器对象中的每一个单一由`Math.random`生成的数值。

```js
const random = {
  [Symbol.iterator]: () => ({
    next: () => ({ value: Math.random() })
  })
}
```

由于上述序列是无限的，尝试使用`Array.from(random)`或`[...random]`转换上述`array`对象为数组将会使我们的程序崩溃。当我们处理这类序列的时候，我们必须额外小心，因为它真的很容易就让我们的浏览器或者`Node`进程崩溃了。

存在一些方法让你可以安全的使用序列，而不用担心启用了无限循环。第一种方法是使用解构来获取序列中的特定值，方法如下所示：

```js
const [one, another] = random
console.log(one)
// <- 0.23235511826351285
console.log(another)
// <- 0.28749457537196577
```

解构无限序列在有的时候又不是那么适用，尤其是当我们希望添加动态条件时，比如说，获取第一个`i`对应的值，或者获取某个满足我们条件的值。在这种情况下，我们最好使用`for..of`。这样我们可以用编程的方式在防止无限循环的前提下尽可能多的迭代元素，下述代码使用`for...of`迭代了我们前面生成的无限序列，但是只要有一个序列值大于`0.8`,迭代将停止。考虑到`Math.random()`返回的值处于0到1之间，这个循环终会结束。

```js
for (const value of random) {
  if (value > 0.8) {
    break
  }
  console.log(value)
}
```

稍后再读上述代码可能会造成理解困难，这是因为上述代码大多集中于当前序列是如何被迭代的。在满足条件之前打印出所有的随机数值，抽象上述逻辑到另一个方法可能会让代码的可读写更高。

我们换个例子，另外一个常见的场景是从一个无限序列或者非常大的序列中抽离出最开始的少量几个元素。尽管你可以直接使用`for...of`和`break`语句。更好的方式是抽离这段代码到一二`take`方法中。下述代码是`take`方法的一种可能实现，它接收两个参数，分别是`sequence`代表待迭代的序列及`amount`需要提取出的值。它将返回一个可被迭代对象，无论何时对象被迭代时，它将依旧所传入的`sequence`返回一个迭代对象。`next`方法和上面的有些许不同，它要求数目至少为1，否者就结束当前序列。

```js
// to rethink
function take(sequence, amount) {
  return {
    [Symbol.iterator]() {
      const iterator = sequence[Symbol.iterator]()
      return {
        next() {
          if (amount-- < 1) {
            return { done: true }
          }
          return iterator.next()
        }
      }
    }
  }
}
```

对于无线序列，我们的代码具有较好的实践，因为上述方法提供了一个退出条件，一旦`amount`数目达到，序列将被终结。现在除了使用循环来获取`random`的值，你可以像下面这样来获取值了：

```js
[...take(random, 2)]
// <- [0.304253100650385, 0.5851333604659885]
```

上述方法允许你转换任何无线序列为有限的。如果你的需求不再是获取前N个序列值，而是获取所有小于第一个0.8的值。你可以修改`take`来满足你的条件，下面我们定义了一个`range`函数，它有默认`low`值为0，`high`参数值为`1`的参数，一旦序列中有值超出这个范围，我们将停止从中获取值。

```js
function range(sequence, low = 0, high = 1) {
  return {
    [Symbol.iterator]() {
      const iterator = sequence[Symbol.iterator]()
      return {
        next() {
          const item = iterator.next()
          if (item.value < low || item.value > high) {
            return { done: true }
          }
          return item
        }
      }
    }
  }
}
```

现在我们不必因为担心序列永不结束而打断`for...of`，我们可以确信迭代终会因为获取到了超出范围外的值而停止。通过这种方法，你写代码的时候不用再那么担心序列是如何生成的，而能更专注于序列能做什么。如下代码所示，你甚至不需要一个`for...of`循环，因为打破条件现在包含在`range`函数中。

```js
const low = [...range(random, 0, 0.8)]
// <- [0.68912092433311, 0.059788614744320, 0.09396195202134]
```

这种抽象复杂代码到其它函数中的方法常常能让我们专注于代码的本来目的，我们避免了使用`for...of`循环并获取到我们想要的序列，还展示了序列可以如何连接组成管道。在这种情况下，我们首先创建了一个多用途的无限`random`序列，然后再通过一系列函数，返回一个推导序列结束时，它会值低于或高于要求的，范围迭代器的一个重要方面是，尽管已经组合了，但范围函数生成的迭代器也可以缓慢迭代，这实际上意味着您可以在映射、过滤和退出条件帮助器中编写多个迭代器。

除了创建迭代器对象技术的影响，我们现在讨论几个实际的例子对我们可以如何从迭代器中受益。

> #### 识别无限序列
> 迭代器不提供任何信息来说明它们生成的序列是不是无限的。这一点类似于著名的停顿问题（如图4-5），通过代码没办法获知序列是否是无限的。
> ![Figure 4-5. The halting problem depicted in an XKCD comic](https://ponyfoo.com/books/practical-modern-javascript/img/pmjs_0405.png)
> 不过一般说来你可以判断一个序列是不是无限序列。是否是无限序列取决于你是否给一个序列添加了退出条件。如果你添加了退出条件`for...of`就不会造成程序崩溃，否则当你对一个无限序列使用`Array.form`或拓展运算符时程序就马上崩溃了。
> 


#### 迭代对象映射图为键值对

有非常多的实践方案受益于转换一个对象为可迭代对象。对象映射，伪数组都天生是可迭代的，上面的随机数字生成器为我们生成了一个无限序列，以及拥有特点属性的类或者纯对象通常都是可迭代，的，它们都可以从以下迭代协议中获益。

一般说来，JS对象被用来表征字符串键值和任意值之间的映射。我们以下面的代码为例，`colors`对象拥有一系列颜色名及其对应的十六进制颜色之间形成映射。有些请求下，你会很喜欢这种毫不费力的迭代不同颜色名，十六进制颜色表征或键值对的能力。

```js
const colors = {
  green: '#0e0',
  orange: '#f50',
  pink: '#e07'
}
```

下述代码表征了一个迭代器用以生成包含`colors`对象中每一种颜色的`[key,value]`序列。考虑到拥有`Symbol.iterator`属性，我们可以非常容易的遍历整个列表。

```js
const colors = {
  green: '#0e0',
  orange: '#f50',
  pink: '#e07',
  [Symbol.iterator]() {
    const keys = Object.keys(colors)
    return {
      next() {
        const done = keys.length === 0
        const key = keys.shift()
        return {
          done,
          value: [key, colors[key]]
        }
      }
    }
  }
}
```

现在我们只需要简单的使用拓展运算符`...`就可以提取出所有的键值对。

```js
console.log([...colors])
// <- [['green', '#0e0'], ['orange', '#f50'], ['pink', '#e07']]
```

实际上我们使用一个大的迭代定义污染了之前的纯粹的`colors`对象可能表明了一个问题，由于迭代行为和储存颜色对没有太大的关系。一个更好的实践办法是提取迭代方法为一个可复用的函数。这样，我们就可以移动`keyValueIterable`到我们的代码中的其它地方在之后还可以在某种程度上复用它。

```js
function keyValueIterable(target) {
  target[Symbol.iterator] = function () {
    const keys = Object.keys(target)
    return {
      next() {
        const done = keys.length === 0
        const key = keys.shift()
        return {
          done,
          value: [key, target[key]]
        }
      }
    }
  }
  return target
}
```

之后我们可以传入`colors`对象为`keyValueIterable`的参数，并把这个对象转换为可迭代对象。由于这个函数对所传入的参数没有特殊的要求，你甚至可以把`keyValueIterable`方法用于任何你想转换其为可迭代键值对的对象上。一旦我们给对象加上`Symbol.iterator`属性，这个对象就是可迭代的了。下面的代码中，我们迭代了键值对但是值打印出`color`：

```js
const colors = keyValueIterable({
  green: '#0e0',
  orange: '#f50',
  pink: '#e07'
})
for (const [ , color] of colors) {
  console.log(color)
  // <- '#0e0'
  // <- '#f50'
  // <- '#e07'
}
```

一个音乐播放器可被看做是另一个有意思的例子。


### 构建多样性的可迭代播放列表

假设，你开发了一个音乐播放器，这个播放器的播放列表可以复制一次然后停止。


